const LOGIN = "LOGIN"
const LOGOUT = 'LOGOUT'
const USER_PROFILE = "USER_PROFILE"
const UNFOLLOWERS = "UNFOLLOWERS"
const REQUESTSENT = "REQUESTSENT"
const FOLLOW = "FOLLOW"
const FOLLOWING_USERS = "FOLLOWING_USERS"
const FOLLOWERS = 'FOLLOWERS'
const TWEETS = "TWEETS"
const PROFILE_LINE_TWEETS ="PROFILE_LINE_TWEETS"
const UPDATE_POST = "UPDATE_POST"
export { LOGIN, LOGOUT, USER_PROFILE, UNFOLLOWERS, REQUESTSENT, FOLLOW, FOLLOWING_USERS, FOLLOWERS, TWEETS ,PROFILE_LINE_TWEETS,UPDATE_POST}