const LOGIN = "LOGIN"
const LOGOUT = 'LOGOUT'
const USER_PROFILE = "USER_PROFILE"
const UNFOLLOWERS = "UNFOLLOWERS"
const REQUESTSENT = "REQUESTSENT"
export { LOGIN, LOGOUT, USER_PROFILE, UNFOLLOWERS ,REQUESTSENT }